### ISSUE TITLE
webui: better styling and interface

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/ach-web-viewer#10]
The initial HTML setup for our webui was quickly tossed together, but we should offer a prettier interface that's more intuitive for users. 

![Screen Shot 2021-06-30 at 3 49 14 PM](https://user-images.githubusercontent.com/120951/124040940-c2c88e00-d9ba-11eb-95ce-da8f614334bc.png)

**Comment by joshsadler** [comment]
@adamdecaf I'm happy to help zshush it up, but `make run` isn't working for me, I may need a quick hand getting started.

**Comment by adamdecaf** [comment]
Thanks @joshsadler! Right now we're printing HTML directly, so there's not a nice template or asset directory to include. Would that be easier for you to modify? 

https://github.com/moov-io/ach-web-viewer/blob/master/pkg/web/web.go#L33

What error are you seeing btw?

**Comment by joshsadler** [comment]
@adamdecaf a template or asset directory would be lovely as opposed to modifying those prints.

I'm running `make run` from the project root and I get:
```
 ach-web-viewer git:(master) make run
pkger -include /migrations -include /configs/config.default.yml
go mod vendor
go build -mod=vendor -ldflags "-X github.com/moov-io/ach-web-viewer.Version=v0.2.1" -o bin/ach-web-viewer github.com/moov-io/ach-web-viewer/cmd/ach-web-viewer
./bin/ach-web-viewer
ts=2021-07-01T23:07:32Z msg="loading config file" level=info version=v0.2.1 app=ach-web-viewer component=Service file=/configs/config.default.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1658eb3]

goroutine 1 [running]:
github.com/moov-io/base/admin.NewServer(0xc0003a1157, 0x5, 0xc0003c6dc0)
	/Users/joshsadler/moov/ach-web-viewer/vendor/github.com/moov-io/base/admin/admin.go:43 +0xb3
github.com/moov-io/ach-web-viewer/pkg/service.bootAdminServer(0xc0003fe4e0, 0x1b4c528, 0xc0003887e0, 0xc0003a1157, 0x5, 0x0, 0x0, 0x0)
	/Users/joshsadler/moov/ach-web-viewer/pkg/service/server.go:65 +0x39
github.com/moov-io/ach-web-viewer/pkg/service.(*Environment).RunServers(0xc00063ff28, 0xc0003fe4e0, 0x0)
	/Users/joshsadler/moov/ach-web-viewer/pkg/service/server.go:22 +0x73
main.main()
	/Users/joshsadler/moov/ach-web-viewer/cmd/ach-web-viewer/main.go:36 +0x325
make: *** [run] Error 2
```

**Comment by adamdecaf** [comment]
Thanks @joshsadler! I've gone ahead and added some templates and a stylesheet under [`webui/`](https://github.com/moov-io/ach-web-viewer/tree/master/webui) for the current views we have. 

Steps for localdev: https://github.com/moov-io/ach-web-viewer/blob/master/docs/RUNNING.md#local-development
